### ISSUE TITLE
Maps not appear

### ISSUE THREAD

**Issue by farhansj** [REANNZ/etcbd-public#1]
<img width="1392" alt="blankmap" src="https://user-images.githubusercontent.com/7088099/28742832-1391ad24-746d-11e7-8303-2d807bc15ede.png">
Hi,

I'm trying to install etcbd for .my eduroam community. However, I have difficulty in loading the map (https://mon.eduroam.my/) . The map screen just turns gray. Besides I need to key in the Google API Key, what else should I set?

Regards

**Comment by farhansj** [comment]
Oops, found the problem... it due to the lat and long was swapped.

**Comment by vladimir-mencl-eresearch** [comment]
Hi, I'm glad you solved it - great to see your site's now up.

Cheers,
Vlad
